### ISSUE TITLE
Only Numerical characters 

### ISSUE THREAD

**Issue by emulatoronlinexyz** [MyScript/interactive-ink-examples-android#12]
Hi there,
1st of all thanks for the great work. 
I just wonder if I can use only numbers and point (1234567890.) for the math education app. 

Thanks in advance

**Comment by MyScriptSupport** [comment]
Hi acizcool,

Thank you for contacting us.

If you want to restrict the symbols and rules for your math education app, you should build a custom math grammar with the symbols and rules that you want to use in your application.
You should follow [this documentation section](https://developer.myscript.com/docs/interactive-ink/1.3/android/advanced/build-custom-resources/#grammar-resource) to learn how to proceed.

Then you should use this grammar in your application according to [this procedure](https://developer.myscript.com/docs/interactive-ink/1.3/android/advanced/custom-recognition/#configuration-files)

If you have any further question, feel free to post them [on our forum](https://developer-support.myscript.com/support/discussions)

Best regards,

Gwenaëlle
