### ISSUE TITLE
Publish UIReferenceImplementation as a standalone library

### ISSUE THREAD

**Issue by ghost** [MyScript/interactive-ink-examples-android#15]
Since including the `UIReferenceImplementation` library is [the recommended way](https://developer.myscript.com/docs/interactive-ink/2.3/android/fundamentals/rendering/#reference-implementation) to start building applications with MyScript's SDK, why not publish it as a library too?

As a developer, in order to start working with the SDK, I'm expecting to do something like:
```groovy
implementation "com.myscript:iink:2.3.2"
implementation "com.myscript:iink-ui:2.3.2" // This is the UIReferenceImplementation library
```
Instead, in the current situation, I have to copy-paste the reference library code from the examples repo, which is not ideal for obvious reasons.

**Comment by MyScriptSupport** [comment]
The UIReferenceImplementation is designed to speed up development and integration for our users.

It is a good starting point per platform that can be customized according to each one's needs.

For this reason, we don't ship it as a library, but as source code, and don't plan to change the way we ship it.
