### ISSUE TITLE
Open Package not working

### ISSUE THREAD

**Issue by imayank91** [MyScript/interactive-ink-examples-android#3]
When I try to open a file using the context menu , i get the below mentioned error.

java.io.IOException: content package archive corrupted

I verified using the File Manger if the file was actually present or not and it was.

**Comment by imayank91** [comment]
I'm using the iink SDK and the file format doesn't matter. I tried opening HTML, JSON, TEXT but nothing is opening.

So what I first did is export a file in any format and then tried opening it. I was Able to save it in an external storage directory but not able to open it

**Comment by MyScriptSupport** [comment]
Dear Maysaini,
If I understand well, you want to import a file an try to recognize the content of it?
Can you please provide with more information, I am not sure to understand what you want to achieve.
Best regards,
Olivier
