### ISSUE TITLE
How do I make the rule lines darker?

### ISSUE THREAD

**Issue by andreysamode** [MyScript/interactive-ink-examples-android#4]
Hello,

How can I make the light grey lines over which I write darker? I'm using the get started example with UIReferenceImplementation folder containing the bulk of the processing.

Thanks.

**Comment by MyScriptSupport** [comment]
Dear Mrandrey,
Currently line color cannot be tuned.
You can find the Styling reference here: https://developer.myscript.com/docs/interactive-ink/1.2/reference/styling/
Best regards,
Olivier

**Comment by andreysamode** [comment]
Thanks. Can the line color be altered in a more direct way somehow? It's difficult to see the lines on my device (Boox Note—eInk screen), and it'd be great to make them black.
I'm using Text Document view, by the way.

**Comment by MyScriptSupport** [comment]
Dear Mrandrey,
My aplogies, as I told you a mistake.
Indeed, this can be done setting the "guide" theme. This can be done as follows on Android: _this.editor.setTheme(“.guide { color: #000; }“);_
Best regards,
Olivier

**Comment by andreysamode** [comment]
Perfect! Many thanks, Olivier.
