### ISSUE TITLE
Lexicon on the fly

### ISSUE THREAD

**Issue by andreysamode** [MyScript/interactive-ink-examples-android#5]
I'd like users of my app to be able to add custom words to the lexicon—for example, fictional names of characters or places. I saw that I can build custom lexicons via an online tool, then compile that into the app. Obviously users of my app won't be able to do that. How can I enable the capacity to add words into the lexicon on the fly? MyScript doesn't seem to take the local dictionary into account. Thanks.

I'm using IInk SKD 1.1 for Android.

Thanks.

**Comment by MyScriptSupport** [comment]
Dear  mrandrey,
thank you for contacting us.
Currently, adding a lexicon on the fly is not yet available, it will be in the coming weeks, with the 1.2.4 release. You will then need to upgrade to this latter release when available.
I keep you updated.
Best regards,
Olivier

**Comment by andreysamode** [comment]
I'm looking forward to it! Thanks, Olivier.

**Comment by MyScriptSupport** [comment]
Dear MRandey,

the 1.3 version of the iink has been released today. You can then compile resources on your device: https://developer.myscript.com/docs/interactive-ink/1.3/android/advanced/build-custom-resources/#on-device

We then recommend you update to this latter one.

Best regards,

Olivier

**Comment by andreysamode** [comment]
This is excellent news! I will give it a try in the next few days. Thanks, Olivier.

**Comment by andreysamode** [comment]
Hello Olivier,

I just tried to follow the suggestion in the doc link and I get the following error:
<img width="558" alt="screen shot 2018-12-24 at 12 22 41 pm" src="https://user-images.githubusercontent.com/444565/50404480-6abfc980-0776-11e9-849b-aa35f851bba3.png">

If I change it to this, it seems to not give an error:
<img width="536" alt="screen shot 2018-12-24 at 12 23 56 pm" src="https://user-images.githubusercontent.com/444565/50404486-7e6b3000-0776-11e9-80ee-584afee9a8ee.png">

Does this mean that the grammar can be loaded dynamically from a string without having to save it to a file and reference in configuration files?

This is what the doc says, which seems a bit off from what I'm experiencing:
<img width="763" alt="screen shot 2018-12-24 at 12 24 55 pm" src="https://user-images.githubusercontent.com/444565/50404498-a22e7600-0776-11e9-9b6d-bfff0c5dc724.png">

Thanks,
Andrey

**Comment by MyScriptSupport** [comment]
Dear Andrey,

thank you for the update.

Currently, the "store" function is to be set with the place where you want the asset to be saved (in a string format).

Once saved in the directory you prefer, the easier is that you set the "configuration-manager.search-path" variable to the corresponding path: https://developer.myscript.com/docs/interactive-ink/1.3/android/fundamentals/interactive-ink-runtime/#back-to-the-example

Your ".conf" file should then be updated with the name of the resource (or you can create a custom conf file), and set it using the "text.configuration.bundle" and text.configuration.name configuration strings: https://developer.myscript.com/docs/interactive-ink/1.3/reference/configuration/#text

Best regards,

Olivier

**Comment by andreysamode** [comment]
So in the following doc example, File file = new File("custom-grammar.res"); should really be String file = new String("custom-grammar.res"); ?

`// 1. Create a recognition assets builder`
`RecognitionAssetsBuilder assetsBuilder = engine.createRecognitionAssetsBuilder();`
`// 2. Define and compile the grammar`
`String grammar = "...";`
`assetsBuilder.compile("Math Grammar", grammar);`
`// 3. Save it to the disc`
`File file = new File("custom-grammar.res");`
`assetsBuilder.store(file);`

Where will it save the custom-grammar.res and what path should I reference in the .conf?

Thanks for adding this feature. I'm excited to get it working.

Andrey

**Comment by MyScriptSupport** [comment]
Dear MRandey,

As said above, you can store it in the path you prefer.

For example, let's say you stored it into the "/sdcard/MyScript/MyResources/" directory, and you stored the other MyScript resources and conf files as follows:

/sdcard/MyScript/conf/en_US.conf
/sdcard/MyScript/en_US/en_US-ak-cur.res
/sdcard/MyScript/en_US/en_US-lk-text.res
/sdcard/MyScript/MyResources/myResource.res

You can then set the configuration-manager.search-path as follows: "/sdcard/MyScript/conf/"

in your conf file, you can add the textwithMyResource configuration as follows:
_Bundle-Version: 1.0
Bundle-Name: en_US
Configuration-Script:
 AddResDir ../resources/

Name: text
Type: Text
Configuration-Script:
 AddResource en_US/en_US-ak-cur.res
 AddResource en_US/en_US-lk-text.res
 EnableAlienCharacters
 SetTextListSize 1
 SetWordListSize 5
 SetCharListSize 1

**Name: textwithMyResource
Type: Text
Configuration-Script:
 AddResource en_US/en_US-ak-cur.res
 AddResource en_US/en_US-lk-text.res
 AddResource MyResources/myResource.res
 EnableAlienCharacters
 SetTextListSize 1
 SetWordListSize 5
 SetCharListSize 1**
 
In order to call the "textwithMyResource" configuration, just set it as follows: conf.setString("text.configuration.name","textwithMyResource");

Best regards,

Olivier

**Comment by andreysamode** [comment]
Thanks, Olivier. I followed your suggestion. The lexicon is being created and stored, but I'm not sure if it's being read, especially when I update it on the fly and reload it with conf.setString("text.configuration.name","textwithMyResource");

It seems to work before I reload it (just on app load), but then stops recognizing my custom lexicon after I make regenerate it and call conf.setString(...).

Is there a way of checking whether a word is in the currently running lexicon programmatically?
That would help me troubleshoot this.

**Comment by MyScriptSupport** [comment]
Dear MRandrey,

First, let me wish you an happy new year.

Thank you for the update. Currently, there is no way to programmatically check a lexicon has been added. What you can do is create a small lexicons (2-3 words), create a simple configuration without the en_US-lk-text.res resource => If properly set, you should be able to recognize these words

Let me know if you ned any other help.

Best regards,

Olivier

**Comment by andreysamode** [comment]
Happy New Year to you as well, Olivier.

Great idea for troubleshooting!

I generated a resource file on [this page](https://developer.myscript.com/support/recognition-assets) with the following contents as Test.res:
```
Abc
Def
Ghi
Jkl
Mno
Pqr
Stu
Vwx
Yz
```

... and a resource file called Andrey.res with the following contents:
```
Andrey
```

Then I altered my settings file to look like this:
```
Bundle-Version: 1.0
Bundle-Name: en_US
Configuration-Script:
 AddResDir ../resources/

Name: text
Type: Text
Configuration-Script:
 AddResource en_US/en_US-ak-cur.res
 AddResource en_US/Test.res
 AddResource en_US/Subset.rez
 EnableAlienCharacters
 SetTextListSize 1
 SetWordListSize 5
 SetCharListSize 1

Name: textCustom
Type: Text
Configuration-Script:
 AddResource en_US/en_US-ak-cur.res
 AddResource en_US/Andrey.res
 AddResource en_US/Subset.rez
 EnableAlienCharacters
 SetTextListSize 1
 SetWordListSize 5
 SetCharListSize 1
```

Now, as expected upon launch, only the Test.res character sequences get recognized. When I try to write "Andrey", it outputs "Ghi" or nothing.

Next, I call the following command on a button press:
```
conf.setString("text.configuration.name","textCustom");
```

I try to write "Andrey", but it still only outputs "Ghi" or nothing.

It appears that even though conf is set, it isn't being read by the editor/engine.

**Comment by MyScriptSupport** [comment]
Dear MRandrey,

currently, the reason is that in a current part, recognition configuration cannot be changed.

If you want to use your new lexicon, you should create a new part and set it the "textCustom" configuration.

Best regards,

Olivier

**Comment by andreysamode** [comment]
Aha, that worked. Thanks, Olivier.

Now, I'm generating the lexicon file on the fly and including it in the config as:
`AddResource /storage/emulated/0/Writer/_lexicon`

... and I'm receiving the following error:
```
01-08 12:39:42.388 26508-26613/com.my.app E/SmartGuideView: Failed to edit block 
"MainBlock": INVALID_OBJECT: error: AddResource _lexicon failed
                                                                         error: failed to read configuration script
                                                                         script exits with 2 errors
```

Since I'm generating it on the fly with the press of a button, it should live in the data directory in storage. When I check it with adb shell, the file is in the path. Is the problem perhaps with how I reference it with an absolute path?

**Comment by MyScriptSupport** [comment]
Dear MRandrey,

thank you for the update,

Currently, this error is raised when the "conf" file cannot be read properly. It is usually related to the en_US.conf file not properly formatted/indented... Can you please store it in a text file, and check it carefully? On the fly generation is likely to cause this.

Best regards,

Olivier

**Comment by andreysamode** [comment]
Here's my en_US.conf file:

```
Bundle-Version: 1.0
Bundle-Name: en_US
Configuration-Script:
 AddResDir ../resources/

Name: text
Type: Text
Configuration-Script:
 AddResource en_US/en_US-ak-cur.res
 AddResource en_US/en_US-lk-text.res
 AddResource /storage/emulated/0/Writer/_lexicon
 AddResource en_US/Subset.rez
 EnableAlienCharacters
 SetTextListSize 1
 SetWordListSize 5
 SetCharListSize 1
```

It looks similar to a working one with the exception of the " AddResource /storage/emulated/0/Writer/_lexicon" line. Are you saying that the .conf file isn't being read or that the "_lexion" file isn't being read?

The error says "INVALID_OBJECT: error: AddResource _lexicon failed". Am I perhaps not including it correctly? Does the .conf support using absolute paths starting with /, or do I perhaps need to somehow use "AddResDir" to add the path to my generated "_lexion" file?

**Comment by MyScriptSupport** [comment]
Dear MRandrey,

currently, in the AddResource lines, you should not have an absolute path, as it will be concatenated with the value provided to the "AddResDir" line.

Best regards,

Olivier

**Comment by andreysamode** [comment]
Hmm... how can I include it then? I can't access the assets or configuration folder for writing, as it's inside an .apk, so then I must write to the storage/sdcard folder. How can I add that folder AssetsDir if not with an absolute path? Or is there another way to add the generated lexicon file to the .conf file?

**Comment by MyScriptSupport** [comment]
Dear MRandrey,

currently, if you have resources in sevral directories, you can set several search directory with the "AddResDir" instruction. You can proceed as follows:
AddResDir directory1
AddResDir directory2
...
AddResource resource1.res
AddResource resource2.res
...

At configuration, it will try to combine directory1 with resource1, and if it cannot find it, it will try with directory2.

Best regards,

Olivier

**Comment by andreysamode** [comment]
Hello Olivier,

The question I have is how to write a generated resource file AND reference it afterward. It appears that if I write the generated resource into local storage/sd card, I can't reference it via absolute path. I also can't write the file into the .apk file structure with default resources, so the ability to generate resources dynamically is there, but the ability to reference and actually them isn't, as far as I can tell.

What do you suggest?

Thanks,
Andrey

**Comment by MyScriptSupport** [comment]
Dear Andrey,

Currently, you can set 2 values for the AddResDir, it will work.

On my side, I just proceeded as follows:
-I created the resource "resourceOnSDCARD.res".
-I stored it on SDCARD, in the /sdcard/resources directory.
-In my conf file, I added the /sdcard/resources directory to AddResDir: _AddResDir /sdcard/resources_
-I created the following configuration:
_Name: textCustom
Type: Text
Configuration-Script:
 AddResource en_US/en_US-ak-cur.res
 AddResource en_US/en_US-lk-text.res
 AddResource resourceOnSDCARD.res
 EnableAlienCharacters
 SetTextListSize 1
 SetWordListSize 5
 SetCharListSize 1_
 
 And call it as follows in my code: _conf.setString("text.configuration.name", "textCustom");_
 
 The resource was properly loaded.
 
 For information, you can find my full conf file below.
 
 Best regards,
 
 Olivier
 
Bundle-Version: 1.0
Bundle-Name: en_US
Configuration-Script:
 AddResDir ../resources/
 AddResDir /sdcard/resources

Name: text
Type: Text
Configuration-Script:
 AddResource en_US/en_US-ak-cur.res
 AddResource en_US/en_US-lk-text.res
 EnableAlienCharacters
 SetTextListSize 1
 SetWordListSize 5
 SetCharListSize 1

Name: textCustom
Type: Text
Configuration-Script:
 AddResource en_US/en_US-ak-cur.res
 AddResource en_US/en_US-lk-text.res
 AddResource resourceOnSDCARD.res
 EnableAlienCharacters
 SetTextListSize 1
 SetWordListSize 5
 SetCharListSize 1

**Comment by andreysamode** [comment]
I got it working with the "AddResDir" setting, like you posted in your example above.
Thanks, Olivier!

**Comment by MyScriptSupport** [comment]
Dear Andrey,

I am glad it it working.

Feel free to contact us (or on our forum: https://developer-support.myscript.com/support/discussions) if you have any question.

Best regards,

Olivier
