### ISSUE TITLE
Option to treat Subscript as regular digit 

### ISSUE THREAD

**Issue by shoaib121** [MyScript/interactive-ink-examples-android#7]
Is there an option to disable that baseline? I want to let users to write digits on multiple lines and the digits that appear on next line either become subscripts or exponents.

**Comment by MyScriptSupport** [comment]
Dear Shoaib,

Currently, I am not sure to understand your question. Are you using the iink SDK or the MyScript calculator?
What are you exactly trying to achieve? Indeed, subscript and superscripts are supported by the iink SDK, but multiple lines equations are not. So, what is your exact use-case? Please explain.

Best regards,

Olivier

**Comment by shoaib121** [comment]
My requirement is multiple line equation but as you already said, is not supported yet. Will this feature be added in future or there is any workaround to bypass it?

**Comment by MyScriptSupport** [comment]
Dear Shoaib,

at present, we cannot commit if/when multiple lines equations will be support in the iink.

Best regards,

Olivier

**Comment by shoaib121** [comment]
Ok thank you so much.
