### ISSUE TITLE
facing an problem that the drawing which user draw get replicated on every pages

### ISSUE THREAD

**Issue by EdbrixDeveloper** [MyScript/interactive-ink-examples-android#8]
Hello team ,
we are developing an education related android application we are integrated interactive ink in our application !!!
so we are facing an problem that the drawing which user draw get replicated on every pages we follow your demo application which given by you on github:
https://github.com/MyScript/interactive-ink-examples-android/tree/master/Demo

will you help us in this to solve this problem 
thanks,
shashank

**Comment by MyScriptSupport** [comment]
Hello Shashank,

For a faster answer, we recommend you creating a post on our developer-forum: https://developer-support.myscript.com/support/discussions

It is quite difficult to provide you with an answer without any further details on your code.
​Could you confirm that you succeeded in running the Demo application when cloned from GitHub without modifying the code (except the certificate) ?

Best regards,

Gwenaëlle

**Comment by MyScriptSupport** [comment]
Close #8
